---
title: "TD Biogéographie Fonctionnelle"
author: "Matthias Grenié"
date: "14 novembre 2018"
output: pdf_document
bibliography: bibliography.bib
---

L'idée de ce TD/TP est de mettre en pratique les concepts étudiés durant le cours sur la diversité fonctionnelle.

Ici on s'intéressera à la biogéographie fonctionnelle [@Violle_emergence_2014].

Utilisation du paquet FD 

## Description de la situation et question

On comprend pas encore les relations traits environnements.
Relation entre traits des plantes & gradient environnemental.

Importance de

On s'intéresse aux traits foliaires car blabla plus variables, différence de stratégie importante etc. Quelle réponse des traits foliaires à l'environnement ? Différentes réponses observées à différentes échelles.


Afin de mettre en évidence les traits les plus importants on utilise le **Community-Weighted Mean** qui représente le trait dominant dans une communauté donnée .

$$
CWM_i = \sum_{i = 1}^{S}p_i T_i,
$$
avec $i$ l'indice d'espèces, $p_i = \frac{N_i}{N}$ l'abondance relative de l'espèce $i$ ($N_i$ l'abondance de l'espèce $i$ et $N$ l'abondance totale dans la communauté) et $T_i$ le trait moyen de l'espèce $i$.

## Chargement des données

D'où viennent ces données ?

Inspection rapide combien de communautés, combien d'espèces, abondances des espèces.

Tableau sites-espèces, tableau espèces-traits & tableau sites-environnement.

## Indices univariés <-> CWM

On observe une communauté, variance de traits etc.


### Cartes

## Relation du CWM aux variables environnementales classiques

### Cartes

## Un meilleur prédicteur des traits foliaires : la longueur de la saison de croissance

### Cartes

## Et la diversité fonctionnelle ?

### Cartes

## Interpolation pour faire des cartes lisses ?

Relation CWM <-> Environnement

Interprétation

[@Miller_Functional_2018; @Muscarella_communityweighted_2016; @Peres-Neto_Linking_2016]
Importance des modèles nuls

Indices multivariés [@Villeger_New_2008] insérer figure de description issue de [@Mouillot_functional_2013]. Permet de comprendre quelle dimension varie.

## Autre façon d'étudier les relations traits environnements : l'analyse RLQ ?

 
